
CREATE DATABASE IF NOT EXISTS login_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE login_db;
CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(100) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS logins (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(100),
  password_masked VARCHAR(255),
  ip VARCHAR(45),
  success TINYINT(1) DEFAULT 0,
  user_agent VARCHAR(255),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
INSERT INTO users (username,password_hash) VALUES ('admin','$2b$12$kvpczwaTG9VC2C.sKdiRaeDPz8ZH3G6Be9X9KiytT6tH3tqV4InGa');